# Generated by Django 4.1.2 on 2022-10-11 17:43

from django.db import migrations, models
import web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[web.validators.phone_validator]),
        ),
    ]
